In [145]:
print(x)
print(a)
a=np.array([[10, 20, 30, 40, 50]])
print(np.concatenate((x,a), axis=0)) #결합 할 (x,y)걸 먼저 적고 축을 써
b=np.arange(1,5).reshape(4,1)
print(b)
print(np.concatenate((x,b),axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[10 20 30 40 50]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [10 20 30 40 50]]
[[1]
 [2]
 [3]
 [4]]
[[ 0  1  2  3  4  1]
 [ 5  6  7  8  9  2]
 [10 11 12 13 14  3]
 [15 16 17 18 19  4]]


In [135]:
print(x)
print(np.delete(x,5))

print(np.delete(x, 1, axis=0)) # 1행이 없어졌어

print(np.delete(x, 1, axis=1)) # 1열이 없어졌어

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  2  3  4]
 [ 5  7  8  9]
 [10 12 13 14]
 [15 17 18 19]]


In [132]:
x
a=[10,20,30,40,50]
a1=[10,20,30,40]
print(np.insert(x, 1, a, axis=0)) #1은 위치 a는 추가되는 값, 축
print(np.insert(x, 1, a1, axis=1))

[[ 0  1  2  3  4]
 [10 20 30 40 50]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0 10  1  2  3  4]
 [ 5 20  6  7  8  9]
 [10 30 11 12 13 14]
 [15 40 16 17 18 19]]


In [130]:
x=np.arange(20).reshape(4,5)
x0=np.append(x, [10,20,30,40,50]) #x에 [] 추가 , 하고 0축
print(x0)
x1=np.append(x, [[10,20,30,40,50]], axis=0) #x에 [] 추가 , 하고 0축 행으로
print(x1)
b=np.array([100,200,300,400,500]).reshape(5,1) #2차원 배열 형태로 붙혀준거야
print(b)
x2=np.append(x1, b, axis=1) #열로 붙어
print(x2)
x3=np.insert(x2, 0, b, axis=1)
print(x3)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 10 20 30 40
 50]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [10 20 30 40 50]]
[[100]
 [200]
 [300]
 [400]
 [500]]
[[  0   1   2   3   4 100]
 [  5   6   7   8   9 200]
 [ 10  11  12  13  14 300]
 [ 15  16  17  18  19 400]
 [ 10  20  30  40  50 500]]
[[100 200 300 400 500   0   1   2   3   4 100]
 [100 200 300 400 500   5   6   7   8   9 200]
 [100 200 300 400 500  10  11  12  13  14 300]
 [100 200 300 400 500  15  16  17  18  19 400]
 [100 200 300 400 500  10  20  30  40  50 500]]


In [ ]:
a=np.arange(10)
print(a)
a = np.append(a, 10) # 10울 추가한거, 한개씩 추가는 append
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [120]:
y=np.resize(x, (10,5))
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [112]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [111]:
print(x)
print('-------')
print(x.reshape(2,2,5)) #x를 3차원 바꾸고 싶어 곱하기만 맞추면 된다.


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
-------
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [107]:
print(x)
print(x.reshape(20)) #x를 1차원 바꾸고 싶어
print(x.ravel()) # 1차원으로 만들어주는거

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
print(x)
print(x.T) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [102]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [101]:
s=time.time() #시작시간
result2=np.sum(x)
e=time.time()
print(result2)
print(e-s)

210
0.00012564659118652344


In [100]:
import time
s=time.time() #시작시간
result=0
for i in x:
  for j in i:
    result+=j
e=time.time() #끝나는 시간
print(result)
print(e-s)

210
0.00022840499877929688


In [97]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [95]:
z=np.arange(1,5).reshape(4,1)
z

array([[1],
       [2],
       [3],
       [4]])

In [96]:
print(x+z)

[[ 2  3  4  5  6]
 [ 8  9 10 11 12]
 [14 15 16 17 18]
 [20 21 22 23 24]]


In [92]:
z=np.arange(1,5)
z

array([1, 2, 3, 4])

In [91]:
print(x)
print(x+y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]]


In [90]:
print(x+5)

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [89]:
y=np.arange(1,6)
y

array([1, 2, 3, 4, 5])

In [88]:
x=np.arange(1,21).reshape(4,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [85]:
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.std(), np.std(a)) #표준편차
print(a.std(axis=0), np.std(a,axis=0))
print(a.std(axis=1), np.std(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2.581988897471611 2.581988897471611
[2.44948974 2.44948974 2.44948974] [2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658] [0.81649658 0.81649658 0.81649658]


In [84]:
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.mean(),np.mean(a))
print(a.mean(axis=0), np.mean(a,axis=0))
print(a.mean(axis=1), np.mean(a,axis=1))
print(np.median(a)) #중앙값

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0 5.0
[4. 5. 6.] [4. 5. 6.]
[2. 5. 8.] [2. 5. 8.]
5.0


In [80]:
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.max(),np.max(a))
print(a.min(),np.min(a))
print(a.max(axis=0), np.max(a,axis=0))
print(a.max(axis=1),np.max(a,axis=1))
print(a.min(axis=0), np.min(a,axis=0))
print(a.min(axis=1), np.min(a,axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
9 9
1 1
[7 8 9] [7 8 9]
[3 6 9] [3 6 9]
[1 2 3] [1 2 3]
[1 4 7] [1 4 7]


In [77]:
print(np.sum(a))
print(np.sum(a, axis=0)) #열별 합계
print(np.sum(a, axis=1)) #행별 합계

45
[12 15 18]
[ 6 15 24]


In [74]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
print(np.exp(a))
print(np.sqrt(a)) # 제곱근

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [69]:
print(b**a)

[       10       400     27000   2560000 312500000]


In [68]:
print(a+b)
print(np.add(a,b))
print(b-a)
print(a*b)
print(a/b)
print(a//b) #정수 몫
print(a%b)

[11 22 33 44 55]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[0 0 0 0 0]
[1 2 3 4 5]


In [ ]:
a=np.arange(1,6)
b=np.arange(10,60,10) #스텝을 생략하면 1이되서 요소가 생략되면 더하기 못한데??????
print(a,b)

[1 2 3 4 5] [10 20 30 40 50]


In [57]:
# 논리 연산자 사용(&, |, ~)
c=a[(a>5) & (a<11)] # and
print(c)
d=a[(a>9) | (a<5 )] # or
print(d)
e=a[~(a%3==0)] #not
print(e)

[]
[1 2 3 4]
[1 2 4 5]


In [56]:
print(a[(a>4) | (a<2)])
print(a[(a>=2) & (a<=4)])
print(a[~(a>3)])

[1 5]
[2 3 4]
[1 2 3]


In [51]:
print(a[a<3])
print(a[a>=3])
print(a[a%2==1])


[1 2]
[3 4 5]
[1 3 5]


In [48]:
a=np.arange(1,6)
print(a)
b=[True, False, False, True, False]
print(a[b])

[1 2 3 4 5]
[1 4]


In [ ]:
a2=np.arange(1,25).reshape(4,6)
print(a2)
print('-------')
print(a2[1])
print('-------')
print(a2[1:3, 1:5])
print('-------')
print(a2[2,:])
print('-------')
print(a2[:3,:3])
print('-------')
print(a2[2:,::-1])
print('-------')
print(a2[::-1, ::-1])
print('-------')


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
-------
[ 7  8  9 10 11 12]
-------
[[ 8  9 10 11]
 [14 15 16 17]]
-------
[13 14 15 16 17 18]
-------
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
-------
[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]
-------
[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]
-------
-------
-------


In [38]:
print(a)
print(a[2][2])
print(a[::2])
print(a[::2,1:3])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
10.0
[[ 0.  1.  2.  3.]
 [ 8.  9. 10. 11.]]
[[ 1.  2.]
 [ 9. 10.]]


In [34]:
a=np.arange(16, dtype=np.float64).reshape(4,4)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
2
(4, 4)
16
float64
8
128


In [30]:
a=np.arange(16)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1
(16,)
16
int64
8


In [24]:
a=np.random.randn(3,3)
print(a)

[[ 1.55633003  1.63441047 -0.72262826]
 [ 0.48368599 -2.41359534  0.86905217]
 [-0.04049616 -0.42546042 -0.38422079]]


In [22]:
a=np.random.rand(3,3)
print(a)

[[0.74208344 0.35172683 0.82126429]
 [0.14960022 0.61411761 0.15857768]
 [0.04779763 0.53146064 0.08370402]]


In [21]:
a=np.random.random((10,2))
print(a)

[[0.88821894 0.49179   ]
 [0.45827136 0.35450404]
 [0.94481468 0.85631082]
 [0.23099994 0.70049457]
 [0.58517826 0.88150815]
 [0.85766197 0.64064882]
 [0.65144076 0.33767624]
 [0.07531643 0.81715556]
 [0.27029496 0.70858448]
 [0.69975347 0.53104056]]


In [19]:
a=np.linspace(1,100,5, endpoint=False)
print(a)

[ 1.  20.8 40.6 60.4 80.2]


In [16]:
a1 = np.arange(1,10)
print(a1)

[1 2 3 4 5 6 7 8 9]


In [13]:
arr40=np.full([10,2],5)
print(arr40)

[[5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]
 [5 5]]


In [11]:
arr1 = np.zeros(10)
print(arr1)
arr2=np.ones(10)
print(arr2)
arr30=np.zeros_like(arr3)
print(arr30)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [8]:
list2=[[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]],[[100,200,300],[400,500,600]]]
arr3=np.array(list2)
print(arr3)

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  20  30]
  [ 40  50  60]]

 [[100 200 300]
  [400 500 600]]]


In [4]:
list2=[[1,2,3],[4,5,6]]
arr = np.array(list2)
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
list1=[1,2,3,4,5]
arr01=np.array(list1)
arr02=np.array([10,20,30,'a'])
#arr01
#arr02
print(arr01)
print(arr02)

[1 2 3 4 5]
['10' '20' '30' 'a']
